// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (SessionSvcSession, error)
	DeleteSession(ctx context.Context, argUuid uuid.UUID) error
	ExtendSession(ctx context.Context, arg ExtendSessionParams) (SessionSvcSession, error)
	GetSession(ctx context.Context, argUuid uuid.UUID) (SessionSvcSession, error)
	RevokeSession(ctx context.Context, argUuid uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
